---
# tasks file for proxy-server
- name: Install squid
  ansible.builtin.package: 
    name: squid
    state: present

- name: Configuration of squid
  ansible.builtin.template:
     src: squid.conf.j2
     dest: /etc/squid/squid.conf
     backup: true
     owner: root
     group: squid
     mode: 0640
  notify: Squid restart
